web/src/pages/Docs.vue

feat: add project name to docs page

---

web/src/pages/Docs.vue

fix the link behaviour and
add support for anchor tags
fixes #28

fix(web): link to documentation

---

web/src/pages/Docs.vue

fix(web): version loaded after switching

---

Dockerfile
docat/Pipfile.lock
web/yarn.lock

Signed-off-by: Benj Fassbind <randombenj@gmail.com>

feat(build): upgrade all dependencies

---

web/src/pages/Docs.vue
web/src/repositories/ProjectRepository.js
web/tests/unit/project-repository.spec.js
web/yarn.lock

fixes #76, thanks for pointing this out @muXxer! :beers:

Fix documentation upload

---

web/public/index.html
web/src/components/Project.vue
web/src/pages/Claim.vue
web/src/pages/Delete.vue
web/src/pages/Docs.vue
web/src/pages/Help.vue
web/src/pages/Home.vue
web/src/pages/Upload.vue

Addresses https://github.com/randombenj/docat/issues/64.

Override titles for pages

---

.github/workflows/docat.yml

Maybe we should test and lint js code in ci

feat(ci): Run frontend test and lint with gh actions

---

web/package-lock.json
web/package.json
web/src/pages/Docs.vue
web/src/repositories/ProjectRepository.js
web/tests/unit/project-repository.spec.js
web/yarn.lock

Git history was messed up and merged accidentally reset on `main`.
//cc @randombenj please review commits before merging
//cc @galaplexus please do a proper rebase next time instead of merging

Fixing: Sorting of versions #142 

---

web/src/components/Layout.vue
web/src/main.js
web/src/pages/Upload.vue

related #154
- Auto-selects first input (so it's clearer that this is a text-form)
- Changes primary color of vue-material to Docat color
- NOTE: This also affects every primary element (e.g. button)

style: improve upload UX

---

web/src/components/Project.vue
web/src/components/ProjectOverview.vue
web/src/repositories/ProjectRepository.js
web/tests/unit/project-component.spec.js
web/tests/unit/project-repository.spec.js

Using localstorage
Most basic UI differentiation between favorite projects and non favorites.
Most direct implementation. Definitely not the best algorithms, but does the trick and nobody will manipulate soo many projects.

feat(web) #74 Favoring projects

---

web/src/components/Project.vue

fix: broken layout

---

web/src/components/Project.vue
web/src/pages/Docs.vue
web/src/repositories/ProjectRepository.js
web/tests/unit/project-component.spec.js
web/tests/unit/project-repository.spec.js

This is a draft PR for the version selection issues that believe to have discovered in https://github.com/docat-org/docat/issues/255.
I didn't get the time so far to test it, nor to update the tests. Feel free to continue :) Otherwise I will finish it as soon as I get some more time to test it better.
Let me know what you think.

Fix latest version selection

---

docat/docat/app.py
docat/tests/test_rename.py

Feat(docat): Add Rename API

---

web/src/pages/Docs.vue

This is in some way a follow-up on #257. The issue at hand is that the drop-down used to select the version is not showing anything when the version with the latest tag was manually inputted into the URL. 
The reason for this is, that the version value from the URL was passed on unaltered to the drop-down. The drop-down however only uses the names (version numbers) and not the tags. 
This means that if a user is opening `/test/latest`, latest will be put into `selectedVersion`. This is then picked up by the drop-down, as it is bound to this variable. It however does not know which version this is, as it only has the version names (eg. 0.0.1, 1.2.3, 3.8.24). This leads it to display nothing. 
My first intuition to fix this was to check if a version exists, matching the current value of …

Fix dropdown not showing version when selecting latests via URL

---

doc/getting-started.md
docat/docat/app.py
docat/tests/test_upload_icon.py
web/src/repositories/ProjectRepository.js
web/tests/unit/project-repository.spec.js

I created this new pull request because I had some trouble with sqashing the commits and switched to a new branch :)
I didn't create a UI for it yet, because of the
upcoming migration to vue 3.
fixes: #75

Feat(Docat): Add Api to upload project icon

---

docat/poetry.lock
web/yarn.lock

chore: dependencies upgrade

---

web/src/components/Layout.vue

feat(web): use a more neutral color (fixes #285)

---

doc/getting-started.md
web/src/pages/Claim.vue

Docs: Document in UI and Docs that Claiming only works once

---

web/src/components/Project.vue

It seems the library we use doesn't escape the content. Because of this, I just added it seperately.
fixes: #299

Fix(web): Tooltips vulnerable to XSS

---

README.md

Docs: Add Documentation on hide ui

---

web/src/pages/Delete.vue

Was the same fix as in #291
fixes: #313

Fix(web): Project Select broken on delete page

---

Dockerfile

Fixes the failing dependabot update builds ...

Fix docker build due to outdated poetry version

---

web/src/style/components/SearchResults.module.css

Now overflows with ellipsis (...)
fixes: #443

Improvement: Fix Search Result overflow

---

Dockerfile

This just takes extra time in the pipeline.
Fixes: #474

Improvement: Remove Lint and Test from docker build

---

web/src/style/components/DocumentControlButtons.module.css
web/src/style/components/Project.module.css

Remove border radius for version select

---

web/src/components/Project.tsx
web/src/style/components/Project.module.css

Display latest version in project card

---

web/src/pages/Docs.tsx

I put the iframe into a useMemo hook that updates when the project, version or page changes.

Fix: Docs blinking when navigating between hashes or pages

---

docat/docat/nginx/default

Fix: Iframing allowed, restrict frame-ancestors to self

---

.github/workflows/docat.yml
Dockerfile
docat/README.md

i think this unblocks #638 at least i run this version on Python 3.12 in a different project //cc @reglim 
(flake8 might still make problems might be worth to switch to ruff here as well)

chore(web): Update to latest poetry 1.6.1

---

.dockerignore

Added docat/tests to .dockerignore

---

web/src/components/IFrame.tsx
web/src/pages/Docs.tsx
web/src/pages/IframePageNotFound.tsx
web/src/style/pages/IframePageNotFound.module.css

Feat: Add not found page for iframe

---

web/yarn.lock

fyi and i will create a bugfix release

chore: update web deps

---

docat/docat/utils.py
docat/tests/test_project.py

Alternative to #854, but with the sorting in the backend.

Feat: Sort Projects Alphabetically

---

README.md

fix typos @ README.md
