- backend/README.md
- backend/app.py
I propose to use the "correct" HTTP verbs and a resource based URI scheme for the backend API endpoints. With doing so the backend API also appeals REST-fanatics :tada:
> Use proper HTTP verbs and REST-like URIs for API endpoints

- Dockerfile
Have a look at dumb init: https://github.com/Yelp/dumb-init
You can now use CTRL+C to quit a docker container
running in foreground.
We can use docker-compose and two containers later on
but this increases complexity and is harder to get started.
fixes #11
> fix: use dumb-init for signal handling in docker

- web/src/components/Layout.vue
removes the second scrollbar which (obviously) shouldn't be there
> fix: layout in docs overview

- .dockerignore
- Dockerfile
To reduce the docker image size
only needed files are copied to the contex.
And the alpine base image is used.
fixes #31
> feat: alpine linux for docker image

- Dockerfile
- web/yarn.lock
on the version 13.1 yarn build fails
also the dependencies are now installed
from the yarn.lock file
> fix(build): upgrade node docker version to 13.6

- web/README.md
- web/src/main.js
- web/src/pages/Docs.vue
- web/src/repositories/ProjectRepository.js
- web/vue.config.js
This change provides more human readable document urls. Instead of just adding the whole
url as the 'location' parameter as an urlencoded parameter. Now the 'real path' is taken:
Before:
```
http://docat.local/#/project/0.0.0/http:%2F%2Fdocat.local%2Fdoc%2Fproject%2F0.0.0%2Finstallation%2F
```
Now:
```
http://docat.local/#/project/0.0.0/installation/
```
> feat: human readable doc path

- .github/workflows/docat.yml
This reverts commit fcbc7bee9d707b7312a7435edb9545630aa604a5.
can be done because mr @randombenj fixed the github setting
> Revert "Ok github why do you need the old python for your check..."

- docat/app.py
- docat/docat/utils.py
- docat/tests/conftest.py
leads to errors like this:
File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
because of that all bytes are converted to hex
> fix(backend): salt can contain non convertable characters

- README.md
There is a missing `\` in the docker command in the readme.
> docs: readme typo

- LICENSE
Since the repo has moved to a Github organisation
> docs: Adapt URL in LICENSE file

- README.md
Prevent "Is a directory: db.json" error when running the docker command
without previously creating the db.json file. This happens because
docker will create every mount point as a directory if it not exists
previously.
Maybe providing a docker-compose file will be also a good idea for the future :)
> docs: Fix docker command in README to not throw error

- web/src/main.js
- web/src/pages/Docs.vue
Hi there :)
Just something small I realized when working with docat. Previously, you always had to specify a version in the url like `do.cat/#/my-awesome-doc/latest/`. When using just `do.cat/#/my-awesome-doc/` it showed an empty page. However, it would be much nicer if it would automatically redirect to the latest version in this case. So I tried to fix that with this Pull Request.
Hope you like the way implemented it :)
> Fix docs page to redirect if no version in url

- Dockerfile
On my system, the base image had an outdated version of alpine and couldn't access the version 1.20 of nginx (only the old 1.18)
Specifying the version of alpine is always a good idea I believe.
> fix(docker) specify strongly base image

- .github/workflows/docat.yml
- Dockerfile
- docat/Makefile
- docat/poetry.lock
- docat/pyproject.toml
- web/package.json
- web/yarn.lock
Otherwise this would not build on a system without python2
but it breaks the upload ui O.o
> chore: upgrade node-sass and all js dependencies

- web/src/main.js
This PR fixes #137.
After some testing, I think this should fix the issue.
When I updated the route with my feature I didn't really think carefully about the order of it. Routes with params should be after the static ones if they are on the same level.
Would you prefer having it even split up into two separate routes?
Like this:
```
{ path: '/:project/', component: Docs },
{ path: '/:project/:version/:location(.*)?', component: Docs }
```
Instead of now (with my fix):
```
{ path: '/:project/:version?/:location(.*)?', component: Docs }
```
> Fix order of document viewer route

- README.md
- docat/docat/app.py
- docat/docat/utils.py
Through Environment variable DOCAT_DB_PATH, defaults to "db.json"
> Allow db.json to be persisted in a custom location

- .github/workflows/docat.yml
Forks and dependabot do not have access to the required secrets to do this operations.
> fix(github-action): run docker push only on main repo

- .github/workflows/docat.yml
The first iteration of this did not work for tag builds.
And using `.fork` is cleaner since this is exposed.
https://github.com/orgs/community/discussions/25217#discussioncomment-3246904
> fix(github-action): run docker push only on main repo II

- Dockerfile
- README.md
- docat/docat/app.py
- docat/docat/nginx/default
- docat/docat/templates/nginx-doc.conf
- docat/docat/utils.py
- docat/tests/conftest.py
- docat/tests/test_project.py
- docat/tests/test_upload.py
- docat/tests/test_utils.py
- web/README.md
- web/src/components/ProjectOverview.vue
- web/src/pages/Delete.vue
- web/src/pages/Docs.vue
- web/src/repositories/ProjectRepository.js
- web/tests/unit/project-repository.spec.js
- web/vue.config.js
This change massively improves the usability while doing local
development. It also fixes #40.
The local development now also proxies the `/api` and `/doc` endpoints
from the  backend (port 5000) through the frontend (port 8080)
making CORS handling simpler during development.
> feat: add project api

- docat/docat/app.py
- docat/tests/test_upload.py
Uploading a document failed with the same name as a broken (no reference) tag resulted in a 500 status code and a stacktrace. To fix this, we now check if a symlink with the same name as the uploaded version exists, and fail if it does.
Also, it is now impossible to create a tag to a version that doesn't exist.
fixes #124
> Fix(docat): Upload of file with name of tag

- docat/docat/app.py
- docat/poetry.lock
- docat/pyproject.toml
- docat/tests/test_upload_icon.py
I added Python-Magic to do that. I also had to adapt the tests because they succeeded even though the content was text not binary.
Is also required for the new docatl push-icon feature.
fixed: #289
> Fix(docat): Icon-Upload Mime Type Check

- web/src/pages/Upload.vue
The form wasn't properly cleared so I added a ref and reset it after uploading.
fixes: #292
> Fix(web): Upload Document twice doesn't work

- web/src/pages/Claim.vue
The ProjectRepository get() method was broken, it needlessly tried to map the result.
fixes: #270
> Fix(web): Claim Token Selection Broken

- web/src/components/ProjectOverview.vue
It is still shown when no projects are present
fixes: #294
> Fix(web): Help Page shown before projects are loaded

- doc/getting-started.md
Fix some spelling errors and make it more consistent.
fixes: #302
> Docs: Reword getting-started.md

- README.md
- doc/getting-started.md
> Docs: Add docatl command examples as alternatives to curl

- docat/docat/app.py
- docat/tests/conftest.py
- docat/tests/test_hide_show.py
> Feat(docat): Add API to hide project versions

- docat/docat/app.py
- docat/docat/utils.py
- docat/tests/test_index.py
The index db connection is now generated in app.py and passed to the utils.
> Fix: Make sure every TinyDB index db instance is closed

- docat/docat/models.py
- docat/docat/utils.py
- docat/tests/test_hide_show.py
- docat/tests/test_project.py
- docat/tests/test_utils.py
- web/src/components/Project.tsx
- web/src/components/ProjectList.tsx
- web/src/data-providers/ProjectDataProvider.tsx
- web/src/models/ProjectsResponse.ts
- web/src/pages/Claim.tsx
- web/src/pages/Delete.tsx
- web/src/pages/Home.tsx
Now the UI doesn't need to make that many requests just to load the number of versions.
fixes: #364
> Improvement: Integrate the number of versions into projects endpoint

- docat/docat/models.py
- docat/docat/utils.py
- docat/tests/test_hide_show.py
- docat/tests/test_project.py
- docat/tests/test_upload_icon.py
- docat/tests/test_utils.py
- web/src/components/Project.tsx
- web/src/models/ProjectsResponse.ts
We don't need to check for each project if an icon exists to prevent flickering, because that is now returned with the projects request.
fixes: #375
> Improvement: Integrate logo into projects endpoint

- docat/.gitignore
- docat/docat/app.py
- docat/docat/utils.py
- docat/tests/test_index.py
The index.json file is now only swapped when indexing is finished, which removes the possiblity of searching with an incomplete index.
fixes: #366
> Improvement: Add Index File switching

- docat/docat/app.py
- docat/docat/models.py
- docat/docat/utils.py
- docat/tests/test_hide_show.py
- docat/tests/test_project.py
- docat/tests/test_upload_icon.py
- docat/tests/test_utils.py
- web/src/components/DocumentControlButtons.tsx
- web/src/components/Project.tsx
- web/src/data-providers/ProjectDataProvider.tsx
- web/src/models/ProjectDetails.ts
- web/src/models/ProjectsResponse.ts
- web/src/pages/Claim.tsx
- web/src/pages/Delete.tsx
- web/src/pages/Docs.tsx
- web/src/repositories/ProjectRepository.ts
- web/src/tests/repositories/ProjectRepository.test.ts
Now we don't have to load any data for each project, greatly reducing the number of requests and improving responsiveness.
We now also return hidden versions, but with the property "hidden" to distinguish them in the UI, which fixes a bug where you couldn't look at hidden versions because they weren't found.
fixes: #367
> Improvement: Integrate Versions into Projects API

- docat/docat/nginx/default
- web/src/components/Project.tsx
- web/src/pages/Docs.tsx
- web/src/pages/EscapeSlashForDocsPath.tsx
- web/src/pages/Home.tsx
- web/src/pages/Search.tsx
- web/src/repositories/ProjectRepository.ts
- web/src/tests/repositories/ProjectRepository.test.ts
The docs page was way too complicated anyway, so I simplified it a bit.
I fixed the following issues:
* Link to docs page resulted in 404, when reloaded
* Browser Back button not working properly (Docs and Search)
* Open in New Tab not working 
fixes: #475, #476, #477, #479
> Fix: Links to Docs page didn't work

- web/src/components/InfoBanner.tsx
- web/src/data-providers/MessageBannerProvider.tsx
- web/src/data-providers/ProjectDataProvider.tsx
- web/src/pages/Claim.tsx
- web/src/pages/Delete.tsx
- web/src/pages/Docs.tsx
- web/src/pages/Upload.tsx
When the user is not on the latest version of a documentation, a warning banner pops up. I had to restructure the MessageBannerProvider a bit for that to work, but I think it's cleaner now.
Fixes: #480
> Feature: Add Info banner if user is not on latest version

- README.md
If the container was mounted that way, the db would not be properly persisted.
fixes: #496
> Docs: Fix Readme wrong instructions for docat persistence

- docat/docat/app.py
- docat/tests/test_upload.py
Upload now tests whether an index.html file is present, and returns the following message if not:
"File successfully uploaded, but no index.html found at root of archive."
Fixes: #509
> Feature: Add warning if index.html is missing in uploaded archive

- README.md
The tag’s value was missing within the README.md for the docatl command.
> fix: docatl tag command within README.md

- docat/docat/nginx/default
I think we should use the index instead of just assuming `/index.html`.
@reglim or was there a good reason to not use index?
> Fix nginx index option url routing

- web/src/pages/Docs.tsx
I couldn't get navigate forward to work, because we have a huge problem with event handlers pushing urls even when we go back a page, so when you click back you can't click forward again. I discussed it with @randombenj and we decided to leave it for the moment.
How I did it was I added an event listener for the `popstate` event that is triggered when the user clicks a navigation button, and triggered back again when it fired, because clicking back once didn't work for unknown reasons.
> Fix: Navigate Back not working on docs page, navigate forward is currently not possible

- web/src/components/IFrame.tsx
Some links like this caused problems:
```<a href="" />```
This was because a.href returned `(page)/index.html`, while I'd expected that to return an empty string. To fix this, I just switched to using `a.getAttribute('href')` which returns the literal value of the link as defined in the html.
> Fix empty links interpreted as not empty, resulted in weird behavior

- Dockerfile
I switched from using node:20.5 to node:20-slim, saving a lot of bandwidth when it has to be pulled. I also moved the yarn install up so it only installs the dependencies when the package.json or yarn.lock files changed.
Cuts build time about 15s when developing in frontend. 
fixes: #639
> Fix: Optimize Docker build

- README.md
- web/src/components/DocumentControlButtons.tsx
- web/src/pages/Docs.tsx
- web/src/style/components/DocumentControlButtons.module.css
Replace the HideUI button with a share button that opens the following modal
fixes #772
> Feature: Add Share modal in place of Hide UI button

- web/src/components/DocumentControlButtons.tsx
- web/src/style/components/DocumentControlButtons.module.css
> Fix: Remove copy button when copying is not supported

- Dockerfile
- README.md
- docat/docat/nginx/default
Allow the image users (server operators) to define their own limit for the Maximal Documentation size.
This approach implements a new Environmental Variable, which can be used to overwrite the default maximum post size of 100MB. It was proposed with the same default to be backwards compatible and simple to setup. 
With this change the operator can adapt the application better to their specific environment.
> Allow configuration of MAX_UPLOAD_SIZE

- web/vite.config.ts
It is already possible to configure the backend port through environment variable (`PORT=XXXX poetry run python -m docat`). In such case, the web component must be able to configure accordingly.
> feat(web): allow to configure proxy port through env var

- web/src/components/IFrame.tsx
- web/src/pages/Docs.tsx
This PR adds a new listener that updates document title to keep in sync with the inner iframe.
Fixes #908
> fix(web): keep title in sync with iframe

- doc/getting-started.md
- web/src/pages/Home.tsx
This PR removes all remaining hash-based routes in the website. This also fixes the bug of `upload` link being incorrect in help page.
> fix(web): remove hash routes in documentation
